version: "3"

services:
  db:
    container_name: Story-Justification-DB
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "27017:27017"
    image: mongo:latest
    restart: always
    volumes:
      - ./mongodb/db:/data/db

  api:
    build: ./story_justification_api
    command: bash -c "npm run build && npm start runserver"
    container_name: Story-Justification-API
    depends_on:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    image: story-justification:api
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - /story-justification/node_modules
      - ./story_justification_api:/story-justification

  webui:
    build: ./story_justification_webui
    command: npm run build
    container_name: Story-Justification-WEBUI
    depends_on:
      - db
    image: story-justification:webui
    volumes:
      - /story-justification/node_modules
      - ./story_justification_webui:/story-justification

  proxy:
    container_name: Story-Justification-PROXY
    depends_on:
      - api
      - webui
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/ssl/certs
      - ./story_justification_webui/dist:/var/www/html
